### ISSUE TITLE
Axon Server on OpenShift

### ISSUE THREAD

**Issue by wittwerch** [AxonIQ/axon-server-dockerfile#4]
We try to run the Axonserver on OpenShift based on the Kubernetes configuration. The path  /opt/axonserver/data is mounted as a persistent volume. However the Axonserver tries to write into the filesystem, which is readonly on OpenShift. This makes it impossible to start.

- The startup.sh writes into  /opt/axonserver/axonserver.properties
- The pid file is placed in the root as well: /opt/axonserver/AxonIQ.pid

It would be great if the path for both files could be either configured using environment variables or they would be stored in /tmp/ by default.

**Comment by bert-laverman** [comment]
The writing in `axonserver.properties` is to allow you to customise the settings at container startup. We did it this way so as to allow people to reuse this one image, but it should be pretty straightforward to bake your own.

I don't know if placing the properties files in `/tmp` is such a good idea, just to circumvent OpenShift's security settings. I think it would be better to use a Kubernetes ConfigMap. That way you get a volume for the properties file. Then use Spring's `spring.config.location` option to point at that directory.

Having Axon Server create the PID file at an alternative location, such as `/tmp/` is currently not possible, as Axon Server creates it in the "current working directory". Sounds like a good idea to let you configure that. We'll see if we can take that along in a later version.

**Comment by wittwerch** [comment]
Yes, using a ConfigMap would surely be the best option!
Do you know whether version 4.1 now supports placing the PID somewhere else? I could not find anything in the release notes.

**Comment by smcvb** [comment]
Hi @wittwerch, 
I can assure you that release 4.1 does support specifying the place of the PID.
You can leverage the `axoniq.axonserver.pid-file-location` property for that. 
We'll make sure to include this into the Reference Guide accordingly.

I assume this has answered your question Christian, so I will be closing this issue for the moment.
