### ISSUE TITLE
Developer Mode not working

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonIQ/axon-server-dockerfile#7]
Tried setting the property as described here https://docs.axoniq.io/reference-guide/operations-guide/setting-up-axon-server/development-mode but couldn't find any functionality for it. Using 4.1.2

I tried `docker run --name axon -p 8024:8024 -p 8124:8124 axoniq/axonserver:4.1.2 /bin/bash -c "java -jar axonserver.jar --axoniq.axonserver.devmode.enabled=true"` as well as setting the properties file but I see no effect

**Comment by gjmwoods** [comment]
@Sam-Kruglov Developer Mode is coming imminently with the 4.2 release. The documentation found its way into the 4.1 branch by mistake and has now been removed to avoid further confusion. Please accept my apologies for this error and for your time spent trying to get this to work.
